@extends('inc.app')

@section('title', 'Generate Course Badge')

@section('content')
<div class="container mt-5 mb-5">
  <div class="card shadow border-0">
    <div class="card-body">
      <h3 class="text-primary mb-4">Course Completion & Badge Generation</h3>

      <!-- 🔍 Search Form -->
      <form id="searchForm" class="mb-4">
        <div class="input-group">
          <input type="text" id="student_id" class="form-control" placeholder="Enter Student ID or NIC">
          <button class="btn btn-primary" type="submit">Search</button>
        </div>
      </form>

      <!-- 📋 Result Section -->
      <div id="resultSection" style="display:none;">
        <h5 class="fw-bold text-secondary mb-3">Registered Courses</h5>
        <table class="table table-bordered align-middle">
          <thead class="table-light">
            <tr>
              <th>#</th>
              <th>Course</th>
              <th>Type</th>
              <th>Intake</th>
              <th>Mode</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody id="courseRows"></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- 🔹 NEW View Certificate Modal -->
<div class="modal fade" id="viewCertModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content border-0 shadow-lg">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title"><i class="ti ti-certificate me-2"></i>Certificate Details</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="viewCertBody">
        <div class="text-center p-5">
          <div class="spinner-border text-primary"></div>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-between">
        <small class="text-muted fst-italic">Generated by Nebula Institute of Technology</small>
        <a id="viewCertLink" href="#" target="_blank" class="btn btn-outline-primary">
          <i class="ti ti-external-link"></i> View Certificate
        </a>
      </div>
    </div>
  </div>
</div>

<script>
document.getElementById('searchForm').addEventListener('submit', async e => {
  e.preventDefault();
  const id = document.getElementById('student_id').value.trim();
  if (!id) return alert('Please enter Student ID or NIC.');

  const res = await fetch('{{ route("badges.search") }}', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
    body: JSON.stringify({ student_id: id })
  });

  const data = await res.json();
  if (!data.success) return alert(data.message);

  const table = document.getElementById('courseRows');
  table.innerHTML = '';
  data.courses.forEach((c, i) => {
    const course = c.course?.course_name || '-';
    const type = c.course?.course_type || '-';
    const intake = c.intake?.batch || '-';
    const mode = c.intake?.intake_mode || '-';
    const status = c.status;
    const allow = (type === 'certificate' && mode === 'Online');

    let action = '';

    if (allow) {
      if (status === 'Completed') {
        if (c.badge && c.badge.verification_code) {
          action = `
            <button class="btn btn-info btn-sm me-2" onclick="viewCertificate('${c.badge.verification_code}')">
              <i class='ti ti-eye'></i> View
            </button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(${c.badge.id}, ${c.id})">
              <i class='ti ti-trash'></i> Cancel
            </button>`;
        } else {
          action = `
            <button class="btn btn-secondary btn-sm me-2" disabled>
              <i class='ti ti-badge'></i> Badge Missing
            </button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(null, ${c.id})">
              <i class='ti ti-trash'></i> Cancel
            </button>`;
        }
      } else {
        action = `
          <button class="btn btn-success btn-sm" onclick="markComplete(${c.id})">
            <i class='ti ti-badge'></i> Mark Completed & Generate Badge
          </button>`;
      }
    } else {
      action = '<span class="text-muted">Not Eligible</span>';
    }

    table.innerHTML += `
      <tr>
        <td>${i + 1}</td>
        <td>${course}</td>
        <td>${type}</td>
        <td>${intake}</td>
        <td>${mode}</td>
        <td>${status}</td>
        <td>${action}</td>
      </tr>`;
  });

  document.getElementById('resultSection').style.display = 'block';
});

async function markComplete(id) {
  if (!confirm('Are you sure you want to mark this course as completed and generate a badge?')) return;

  try {
    const res = await fetch('{{ route("badges.complete") }}', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
      body: JSON.stringify({ id })
    });

    const data = await res.json();
    alert(data.message);

    if (data.success) {
      const studentId = document.getElementById('student_id').value.trim();

      if (!studentId) {
        console.warn('⚠️ No student ID found to refresh.');
        return;
      }

      // show temporary message in table
      const table = document.getElementById('courseRows');
      table.innerHTML = `
        <tr>
          <td colspan="7" class="text-center text-primary p-3">
            <div class="spinner-border text-primary me-2"></div>
            Refreshing student details...
          </td>
        </tr>`;

      // 🕐 wait 1s to ensure DB changes are committed
      setTimeout(async () => {
        console.log('🔄 Re-fetching student:', studentId);
        await reloadStudentDetails(studentId);
      }, 1000);
    }
  } catch (err) {
    console.error('❌ Error completing course:', err);
    alert('Something went wrong while generating the badge. Check console for details.');
  }
}


async function viewCertificate(code) {
  const body = document.getElementById('viewCertBody');
  const link = document.getElementById('viewCertLink');
  body.innerHTML = `<div class="text-center p-5"><div class="spinner-border text-primary"></div></div>`;
  
  const res = await fetch(`/badges/details/${code}`);
  const html = await res.text();

  // Show modal content
  body.innerHTML = html;
  link.href = `/verify-badge/${code}`;
  new bootstrap.Modal(document.getElementById('viewCertModal')).show();
}

async function cancelBadge(badgeId, registrationId) {
  if (!confirm('Are you sure you want to cancel this certificate?')) return;
  const res = await fetch('{{ route("badges.cancel") }}', {
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
    body: JSON.stringify({ badge_id: badgeId, registration_id: registrationId })
  });
  const data = await res.json();
  alert(data.message);
  if (data.success) location.reload();
}

async function reloadStudentDetails(studentId) {
  const res = await fetch('{{ route("badges.search") }}', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
    body: JSON.stringify({ student_id: studentId })
  });

  const data = await res.json();
  if (!data.success) return alert(data.message);

  const table = document.getElementById('courseRows');
  table.innerHTML = '';
  data.courses.forEach((c, i) => {
    const course = c.course?.course_name || '-';
    const type = c.course?.course_type || '-';
    const intake = c.intake?.batch || '-';
    const mode = c.intake?.intake_mode || '-';
    const status = c.status;
    const allow = (type === 'certificate' && mode === 'Online');

    let action = '';

    if (allow) {
      if (status === 'Completed') {
        if (c.badge && c.badge.verification_code) {
          action = `
            <button class="btn btn-info btn-sm me-2" onclick="viewCertificate('${c.badge.verification_code}')">
              <i class='ti ti-eye'></i> View
            </button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(${c.badge.id}, ${c.id})">
              <i class='ti ti-trash'></i> Cancel
            </button>`;
        } else {
          action = `
            <button class="btn btn-secondary btn-sm me-2" disabled>
              <i class='ti ti-badge'></i> Badge Missing
            </button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(null, ${c.id})">
              <i class='ti ti-trash'></i> Cancel
            </button>`;
        }
      } else {
        action = `
          <button class="btn btn-success btn-sm" onclick="markComplete(${c.id})">
            <i class='ti ti-badge'></i> Mark Completed & Generate Badge
          </button>`;
      }
    } else {
      action = '<span class="text-muted">Not Eligible</span>';
    }

    table.innerHTML += `
      <tr>
        <td>${i + 1}</td>
        <td>${course}</td>
        <td>${type}</td>
        <td>${intake}</td>
        <td>${mode}</td>
        <td>${status}</td>
        <td>${action}</td>
      </tr>`;
  });

  document.getElementById('resultSection').style.display = 'block';
}

</script>
@endsection
